=== ImmerSie/TutorMe/web/WEB-INF/bookings.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    
    
    <xs:simpleType name="id">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="9999999"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][a-z]+(\s[A-Z][a-z]+)*"/>     
        </xs:restriction>
    </xs:simpleType>
    

    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z_\.]+@[a-z\-][a-z\-]+(\.[a-z\-][a-z\-]+)+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="subject">
        <xs:restriction base="xs:string">
            <xs:pattern value="(WSD)|(SEP)|(USP)|(AppProg)|(MobileApp)"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="status">
        <xs:restriction base="xs:string">
            <xs:pattern value="(active)|(cancelled)|(complete)"/>
        </xs:restriction>
    </xs:simpleType>

  
  
    <!-- Insert your element declarations here -->
 
    <xs:element name="bookings"> 
        <xs:complexType>
            <xs:sequence>   
                <xs:element name="booking" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="bookingID" type="id"/>
                            <xs:element name="tutorName" type="name"/>
                            <xs:element name="tutorEmail" type="email"/>
                            <xs:element name="subject" type="subject"/>
                            <xs:element name="studentName" type="name"/>     
                            <xs:element name="studentEmail" type="email"/>
                            <xs:element name="status" type="status"/>                    
                        </xs:sequence>                     
                    </xs:complexType>  
                </xs:element>
           
            </xs:sequence>
        </xs:complexType>   
    </xs:element>
    
    
</xs:schema>

=== ImmerSie/TutorMe/web/bookings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<bookings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="bookings.xsd">
    <booking>
        <bookingID>1</bookingID>
        <tutorName>Ryan</tutorName>
        <tutorEmail>ryan@gmail.com</tutorEmail>
        <subject>WSD</subject>
        <studentName>Sarah</studentName>
        <studentEmail>firstEmail@yahoo.com</studentEmail>
        <status>active</status>
    </booking>
    <booking>
        <bookingID>2</bookingID>
        <tutorName>Luke</tutorName>
        <tutorEmail>luke@gmail.com</tutorEmail>
        <subject>SEP</subject>
        <studentName>Simran</studentName>
        <studentEmail>simran@gmail.com</studentEmail>
        <status>active</status>
    </booking>
</bookings>
