=== ImmerSie/TutorMe/web/WEB-INF/tutors.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    
    

    <xs:simpleType name="date">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][a-z]+(\s[A-Z][a-z]+)*"/>
           
        </xs:restriction>
    </xs:simpleType>
    

    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z_\.]+@[a-z\-][a-z\-]+(\.[a-z\-][a-z\-]+)+"/>
        </xs:restriction>
    </xs:simpleType>

   <xs:simpleType name="userType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="password">
        <xs:restriction base="xs:string">
            <xs:pattern value=".+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="subject">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{1}[a-zA-Z]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="status">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]+"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- Insert your element declarations here -->
 
    <xs:element name="tutors"> 
        <xs:complexType>
            <xs:sequence>   
                <xs:element name="tutor" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="name"/>
                            <xs:element name="email" type="email"/>
                            <xs:element name="password" type="password"/>
                            <xs:element name="birthday" type="date"/>
                            <xs:element name="userType" type="usertype"/>     
                            <xs:element name="subject" type="subject"/>
                            <xs:element name="status" type="status"/>                    
                        </xs:sequence>                     
                    </xs:complexType>  
                </xs:element>
           
            </xs:sequence>
        </xs:complexType>   
    </xs:element>
    
    
</xs:schema>

=== ImmerSie/TutorMe/web/WEB-INF/tutors.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<tutors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="tutors.xsd">
    <tutor>
        <name>Ryan</name>
        <email>ryan@gmail.com</email>
        <password>blahblah</password>
        <birthday>January 2</birthday>
        <userType>Tutor</userType>
        <subject>WSD</subject>
        <status>available</status>
    </tutor>
    <tutor>
        <name>Georges</name>
        <email>georges@gmail.com</email>
        <password>blahblah</password>
        <birthday>January 2</birthday>
        <userType>Tutor</userType>
        <subject>WSD</subject>
        <status>available</status>
    </tutor>
    <tutor>
        <name>Luke</name>
        <email>luke@gmail.com</email>
        <password>blahblah</password>
        <birthday>January 2</birthday>
        <userType>Tutor</userType>
        <subject>AppProg</subject>
        <status>available</status>
    </tutor>
      <tutor>
        <name>Brannigan</name>
        <email>brannigan@gmail.com</email>
        <password>blahblah</password>
        <birthday>January 4</birthday>
        <userType>Tutor</userType>
        <subject>USP</subject>
        <status>unavailable</status>
    </tutor>
      <tutor>
        <name>Dennis</name>
        <email>dennis@gmail.com</email>
        <password>blahblah</password>
        <birthday>December 2</birthday>
        <userType>Tutor</userType>
        <subject>MobileApp</subject>
        <status>available</status>
    </tutor>
</tutors>
